services:
    php:
        build:
            context: .
            dockerfile: services/php-fpm/Dockerfile
        container_name: php-fpm
        restart: unless-stopped
        user: '1000:1000'
        volumes:
            - './:/var/www/app:delegated'
        networks:
            - sail
    nginx:
        build:
            context: .
            dockerfile: services/nginx/Dockerfile
        container_name: nginx
        ports:
            - '7000:80'
        depends_on:
            - php
        networks:
            - sail
        volumes:
            - './:/var/www/app:delegated'
    meilisearch:
        image: 'getmeili/meilisearch:latest'
        ports:
            - '${FORWARD_MEILISEARCH_PORT:-7700}:7700'
        environment:
            MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
        volumes:
            - 'sail-meilisearch:/meili_data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - wget
                - '--no-verbose'
                - '--spider'
                - 'http://127.0.0.1:7700/health'
            retries: 3
            timeout: 5s
    mongodb:
        image: 'mongodb/mongodb-atlas-local:latest'
        environment:
            - 'MONGODB_INITDB_ROOT_USERNAME=${MONGODB_USERNAME:-}'
            - 'MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD:-}'
        volumes:
            - 'sail-mongodb:/data/db'
        ports:
            - '${FORWARD_MONGODB_PORT:-27017}:27017'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mongosh
                - 'mongodb://localhost:27017/admin'
                - '--eval=db.runCommand({ping:1})'
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-meilisearch:
        driver: local
    sail-mongodb:
        driver: local
