services:
    php:
        build:
            context: .
            dockerfile: services/php-fpm/Dockerfile
        container_name: php-fpm
        restart: unless-stopped
        user: "1000:1000"
        volumes:
            - ./:/var/www/app:delegated
        networks:
            - sail

    nginx:
        build:
            context: .
            dockerfile: services/nginx/Dockerfile
        container_name: nginx
        ports:
            - "7000:80"
        depends_on:
            - php
        networks:
            - sail
        volumes:
            - ./:/var/www/app:delegated

networks:
    sail:
        driver: bridge
